CREATE TABLE "GITHUB_PRVT"."GITHUB_LOGIN"
   (	
   "GITHUB_ID" NUMBER NOT NULL,
	"USERNAME" VARCHAR2(50) NOT NULL, 
	"PASSWORD" VARCHAR2(10) NOT NULL, 
	"DOB" DATE NOT NULL, 
	"EMAILID" VARCHAR2(50) NOT NULL, 
	"MOBILENO" NUMBER DEFAULT 0000000000 NOT NULL,
  };
  
   CREATE TABLE "GITHUB_PRVT"."GITHUB" 
   (	"GITHUB_ID" NUMBER NOT NULL ENABLE, 
	"APPLICATION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "GITHUB_PK" PRIMARY KEY ("GITHUB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;